# Generated by Django 3.0.1 on 2022-05-25 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0016_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oth.Phase'),
        ),
    ]
